"""Memory compression output format definitions.

Extends the existing Aleph tag-based format with [ALEPH:MEMORY:1.0] section
for compressed conversation transcripts and session history.
"""

from __future__ import annotations

from aleph.emit.format import FORMAT_VERSION

MEMORY_HEADER = f"[ALEPH:MEMORY:{FORMAT_VERSION}]"

# Section tags within a memory block
DECISIONS_TAG = "[DECISIONS]"
DECISIONS_END = "[/DECISIONS]"
CONCLUSIONS_TAG = "[CONCLUSIONS]"
CONCLUSIONS_END = "[/CONCLUSIONS]"
OPEN_QUESTIONS_TAG = "[OPEN_QUESTIONS]"
OPEN_QUESTIONS_END = "[/OPEN_QUESTIONS]"
CODE_CHANGES_TAG = "[CODE_CHANGES]"
CODE_CHANGES_END = "[/CODE_CHANGES]"
ERRORS_TAG = "[ERRORS_ENCOUNTERED]"
ERRORS_END = "[/ERRORS_ENCOUNTERED]"
CONTEXT_TAG = "[CONTEXT]"
CONTEXT_END = "[/CONTEXT]"
DICT_TAG = "[DICT]"
DICT_END = "[/DICT]"
STATS_TAG = "[STATS]"
STATS_END = "[/STATS]"

# Resume briefing tags (project.aleph.resume)
RESUME_HEADER = f"[ALEPH:RESUME:{FORMAT_VERSION}]"
RESUME_INFERENCES_TAG = "[TOP_INFERENCES]"
RESUME_INFERENCES_END = "[/TOP_INFERENCES]"
RESUME_FLAGS_TAG = "[FLAGS]"
RESUME_FLAGS_END = "[/FLAGS]"
RESUME_PATCHES_TAG = "[PENDING_PATCHES]"
RESUME_PATCHES_END = "[/PENDING_PATCHES]"
RESUME_LEARNED_TAG = "[LEARNED]"
RESUME_LEARNED_END = "[/LEARNED]"
RESUME_DECISIONS_TAG = "[KEY_DECISIONS]"
RESUME_DECISIONS_END = "[/KEY_DECISIONS]"
